### ISSUE TITLE
SMTP - Not required fields mandatory during setup

### ISSUE THREAD

**Issue by BeDazzleMe** [olsson82/rivendellweb#19]
During the web based setup, when selecting "no" for SMTP authentication, the username and password fields both remain mandatory.
These fields should be either hidden or allowed to be empty if no SMTP authentication is required.

**Comment by olsson82** [comment]
Thanks for reporting, will fix this to the next update.

**Comment by BeDazzleMe** [comment]
Thank you.

**Comment by olsson82** [comment]
This issue has now been fixed in 0cde4e0
Closing this issue now.
