### ISSUE TITLE
Cannot login after installation

### ISSUE THREAD

**Issue by BeDazzleMe** [olsson82/rivendellweb#20]
I have installed on ubuntu, following the instructions after installing RD4 on the same machine (client mode).
The RD4 client functions work and the node can connect to the RD4 database host as per normal.

When I point my browser at the new RD4 node running Rivendell Web, it completes setup fine and then presents the login screen.

No matter which username / password I enter, none of them work. A pop-up says check username/password.

I have tried Linux based users, RD based users and both Linux + RD users (ie: rd) but none allow me to login.

Is there something I am missing or not doing right ?

Many thanks.

**Comment by olsson82** [comment]
You need to use your Rivendell regular user that you setup in RDAdmin and enable web rights for the user.

If you don't have web rights active on the user you can not login.

/Andreas

**Comment by BeDazzleMe** [comment]
Hello Andreas,

Thank you, that's now working.

Might be a good idea to put that requirement in the documentation.

Darren.
