### ISSUE TITLE
/dash not working

### ISSUE THREAD

**Issue by mysteryaudiodev** [olsson82/rivendellweb#32]
After a successful log into the panel, /dash says "not found". 

Not Found
The requested URL was not found on this server.

I have checked the files, and all installation files seem to be correct.

**Comment by olsson82** [comment]
Did you clone the repo or did you use a release version ?

Have you enable rewrite on the server? See Installation section in document.

Also check so you have the hidden files with ls -all and look for .htaccess file.

**Comment by mysteryaudiodev** [comment]
Apologies, I put override all on the wrong option
